debug_msg() {
    if [ "$ZSHRC_DEBUG" = "" ]; then
        return
    fi
    
    message="$1"
    1>&2 echo "$message"
}

if ! command -v "realpath" > /dev/null 2>&1; then
    debug_msg "realpath not found"
    return
fi

directory="$(dirname "$(realpath "${(%):-%x}")")"
for file in $(find "$directory" -maxdepth 4 -name zshrc.sh); do
    debug_msg "initialize: $file"
    . "$file"
done

unset debug_msg

autoload -Uz compinit && compinit
