---
- tags: [graphical, firefox]
  block:
    - when: not (darwin or archlinux)
      block:
        - name: unimplemented
          benfiola.dotfiles.empty: {}

    - when: darwin
      block:
        - name: brew install homebrew/cask/firefox
          community.general.homebrew_cask:
            name: homebrew/cask/firefox
            path: "{{brew_path}}"

        - name: install enterprise profile
          ansible.builtin.unarchive:
            dest: /Applications/Firefox.app/Contents/Resources
            src: "{{dotfiles_path}}/roles/firefox/files/enterprise_policy.zip"

        - name: unquarantine firefox
          when: darwin
          ansible.builtin.command:
            cmd: xattr -d com.apple.quarantine /Applications/Firefox.app
          changed_when: false
          failed_when: false

    - when: archlinux
      block:
        - name: pacman install firefox
          become: true
          community.general.pacman:
            name:
              - firefox

        - name: create enterprise profile directory
          become: true
          ansible.builtin.file:
            path: "/usr/lib/firefox"
            state: directory
            recurse: true

        - name: install enterprise profile
          become: true
          ansible.builtin.unarchive:
            dest: "/usr/lib/firefox"
            src: "{{dotfiles_path}}/roles/firefox/files/enterprise_policy.zip"
