---
- tags: [optional, xbox]
  block:
    - when: not archlinux
      block:
        - name: unimplemented
          benfiola.dotfiles.empty: {}

    - when: archlinux
      block:
        - name: pacman aur install xone-dongle-firmware
          ansible.builtin.include_role:
            name: benfiola.dotfiles.utils
            tasks_from: install-pacman-aur.yaml
          vars:
            url: https://aur.archlinux.org/xone-dongle-firmware.git
            package: xone-dongle-firmware

        - name: pacman aur install xone-dkms-git
          ansible.builtin.include_role:
            name: benfiola.dotfiles.utils
            tasks_from: install-pacman-aur.yaml
          vars:
            url: https://aur.archlinux.org/xone-dkms-git.git
            package: xone-dkms
