---
- tags: [minimal, user]
  block:
    - name: configure sudoers
      become: true
      ansible.builtin.blockinfile:
        path: /etc/sudoers.d/99-{{user.name}}
        create: true
        marker: "# {mark} ansible:({{role_name}}) -->"
        block: |
          {{user.name}} ALL=(ALL) NOPASSWD: ALL
          Defaults:{{user.name}} env_reset
          Defaults:{{user.name}} env_keep -= "PATH"
          Defaults:{{user.name}} env_delete += "PATH"
        validate: visudo -cf %s

    - name: create .profile.d directory
      ansible.builtin.file:
        path: "{{user_profiled_path}}"
        state: directory
...