---
- tags: [optional, steam]
  block:
    - when: not (darwin or archlinux)
      block:
        - name: unimplemented
          benfiola.dotfiles.empty: {}

    - when: darwin
      block:
        - name: brew install homebrew/cask/steam
          community.general.homebrew_cask:
            name: homebrew/cask/steam
            path: "{{brew_path}}"

    - when: archlinux
      block:
        - name: pacman install steam
          become: true
          community.general.pacman:
            name:
              - steam
