# creates a systemd service unit with "{{name}}" at "{{scope}}"
# "{{scope}}" must be either 'user' or 'system' (default is 'system')
- vars:
    scope: "{{scope | default('system')}}"
    become: "{{scope == 'system'}}"
    folders:
      user: "{{user.home}}/.config/systemd/user"
      system: /usr/lib/systemd/system
    folder: "{{folders[scope]}}"
  block:
    - name: create {{scope}} service folder
      become: "{{become}}"
      ansible.builtin.file:
        path: "{{folder}}"
        recurse: true
        state: directory

    - name: create {{name}}.service
      become: "{{become}}"
      ansible.builtin.template:
        src: systemd.service.j2
        dest: "{{folder}}/{{name}}.service"
        mode: "0644"
