# creates a desktop file for "{{name}}" with scope "{{scope}}".
# "{{scope}}" can be 'user' or 'system' (defaults to 'system')
- vars:
    scope: "{{scope | default('system')}}"
    become: "{{scope == 'system'}}"
    folders:
      user: "{{user.home}}/.local/share/applications"
      system: /usr/share/applications
    folder: "{{folders[scope]}}"
  block:
    - name: create {{scope}} applications folder
      become: "{{become}}"
      ansible.builtin.file:
        recurse: true
        path: "{{folder}}"
        state: directory

    - name: create {{name}}.desktop
      become: "{{become}}"
      ansible.builtin.template:
        src: desktop.j2
        dest: "{{folder}}/{{name}}.desktop"
        mode: "0644"
