# installs a '{{binary}}' via a script provided at '{{url}}', supplying '{{args}}' if specified
# if '{{binary}}' exists, install is skipped
# if '{{become}}' exists, script is elevated to '{{become}}' prior to execution
- name: check binary exists
  ansible.builtin.stat:
    path: "{{binary}}"
  register: binary_exists

- name: install binary
  when: not binary_exists.stat.exists
  block:
    - name: create temp file
      benfiola.dotfiles.temp_file: {}
      register: temp_path

    - name: make temp file executable
      ansible.builtin.file:
        path: "{{temp_path.path}}"
        mode: 0755

    - name: downlad script
      ansible.builtin.get_url:
        url: "{{url}}"
        dest: "{{temp_path.path}}"
        force: true

    - name: run script
      become: "{{become | default(false)}}"
      ansible.builtin.command:
        cmd: "{{temp_path.path}} {{args | default('')}}"
        creates: "{{binary}}"
