---
- tags: [minimal, git]
  block:
    - when: not (true)
      block:
        - name: unimplemented
          benfiola.dotfiles.empty: {}

    - when: true
      vars:
        git_config:
          commit.gpgsign: true
          gpg.format: ssh
          init.defaultbranch: main
          user.name: Ben Fiola
          user.email: benfiola@gmail.com
          user.signingkey: "{{user.home}}/.ssh/{{git_remote}}"
      block:
        - name: create git config
          ansible.builtin.include_role:
            name: benfiola.dotfiles.git
            tasks_from: create-git-config.yaml
          loop:
            - github.com
          loop_control:
            loop_var: git_remote
