---
- tags: [minimal, source]
  block:
    - when: not true
      block:
        - name: unimplemented
          benfiola.dotfiles.empty: {}

    - when: true
      block:
        - name: link zshrc file
          ansible.builtin.file:
            src: "{{dotfiles_path}}/roles/source/files/profile.sh"
            path: "{{user_profiled_path}}/00-source.sh"
            state: link
