---
- tags: [graphical, ghostty]
  block:
    - when: not darwin
      block:
        - name: unimplemented
          benfiola.dotfiles.empty: {}

    - when: darwin
      block:
        - name: brew install homebrew/cask/ghostty
          community.general.homebrew_cask:
            name: homebrew/cask/ghostty
            path: "{{brew_path}}"

        - block:
            - name: create config directory
              ansible.builtin.file:
                path: "{{config_path | dirname}}"
                state: directory
                recurse: true

            - name: symlink config
              ansible.builtin.file:
                src: "{{dotfiles_path}}/roles/ghostty/files/config"
                path: "{{config_path}}"
                state: link
                force: true
          vars:
            config_path: "{{user.home}}/Library/Application Support/com.mitchellh.ghostty/config"
