---
- tags: [minimal, docker]
  block:
    - when: not ((debian or archlinux or darwin) and not wsl)
      block:
        - name: unimplemented
          benfiola.dotfiles.empty: {}

    - when: not wsl
      block:
        - when: debian
          block:
            - name: apt add docker signing key
              become: true
              ansible.builtin.apt_key:
                url: https://download.docker.com/linux/ubuntu/gpg

            - name: apt add docker repository
              become: true
              ansible.builtin.apt_repository:
                repo: "{{repositories[architecture]}}"
              vars:
                repositories:
                  amd64: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{release}} stable
                  arm64: deb [arch=arm64] https://download.docker.com/linux/ubuntu {{release}} stable

            - name: apt install docker
              become: true
              ansible.builtin.apt:
                update_cache: true
                package:
                  - containerd.io
                  - docker-ce
                  - docker-ce-cli
                  - docker-compose-plugin

        - when: archlinux
          block:
            - name: pacman install docker
              become: true
              community.general.pacman:
                name:
                  - docker
                  - docker-buildx
                  - docker-compose

            - name: systemd enable docker service
              become: true
              ansible.builtin.systemd:
                name: docker
                state: started
                enabled: true

        - when: archlinux or debian
          block:
            - name: add docker group
              become: true
              ansible.builtin.group:
                name: docker

            - name: add user to docker group
              become: true
              ansible.builtin.user:
                name: "{{user.name}}"
                append: true
                groups: docker

        - when: darwin
          block:
            - name: brew install docker
              community.general.homebrew:
                name:
                  - colima
                  - docker
                  - docker-buildx
                  - docker-compose
                  - docker-credential-helper
                path: "{{brew_path}}"

            - name: create docker cli-plugins directory
              ansible.builtin.file:
                path: "{{user.home}}/.docker/cli-plugins"
                state: directory
                recurse: true

            - name: symlink docker-buildx to docker cli plugins
              ansible.builtin.file:
                src: "{{brew_path}}/docker-buildx"
                path: "{{user.home}}/.docker/cli-plugins/docker-buildx"
                state: link

            - name: symlink docker-compose to docker cli plugins
              ansible.builtin.file:
                src: "{{brew_path}}/docker-compose"
                path: "{{user.home}}/.docker/cli-plugins/docker-compose"
                state: link
