---
- hosts: all
  tasks:
    - block:
        # base facts
        - import_role: name=benfiola.dotfiles.facts

        # user (provides facts for user profile personalization)
        - import_role: name=benfiola.dotfiles.user

        # package managers
        - import_role: name=benfiola.dotfiles.apt
        - import_role: name=benfiola.dotfiles.brew
        - import_role: name=benfiola.dotfiles.pacman

        # package managers installed by other package managers
        - import_role: name=benfiola.dotfiles.flatpak
        - import_role: name=benfiola.dotfiles.mas
        - import_role: name=benfiola.dotfiles.snap

        # system personalization and configuration
        - import_role: name=benfiola.dotfiles.fonts
        - import_role: name=benfiola.dotfiles.locale
        - import_role: name=benfiola.dotfiles.kde
        - import_role: name=benfiola.dotfiles.macos

        # wine + proton needed for lutris + steam
        - import_role: name=benfiola.dotfiles.wine
        - import_role: name=benfiola.dotfiles.proton

        # other apps depend on private/public ssh keys being installed
        - import_role: name=benfiola.dotfiles.ssh

        # misc applications and tools
        - import_role: name=benfiola.dotfiles.c
        - import_role: name=benfiola.dotfiles.alfred
        - import_role: name=benfiola.dotfiles.bitwarden
        - import_role: name=benfiola.dotfiles.chromium
        - import_role: name=benfiola.dotfiles.contexts
        - import_role: name=benfiola.dotfiles.discord
        - import_role: name=benfiola.dotfiles.docker
        - import_role: name=benfiola.dotfiles.fat
        - import_role: name=benfiola.dotfiles.gimp
        - import_role: name=benfiola.dotfiles.git
        - import_role: name=benfiola.dotfiles.iterm2
        - import_role: name=benfiola.dotfiles.konsole
        - import_role: name=benfiola.dotfiles.ls
        - import_role: name=benfiola.dotfiles.lutris
        - import_role: name=benfiola.dotfiles.magnet
        - import_role: name=benfiola.dotfiles.open_vm_tools
        - import_role: name=benfiola.dotfiles.proton
        - import_role: name=benfiola.dotfiles.source
        - import_role: name=benfiola.dotfiles.spotify
        - import_role: name=benfiola.dotfiles.starship
        - import_role: name=benfiola.dotfiles.steam
        - import_role: name=benfiola.dotfiles.vim
        - import_role: name=benfiola.dotfiles.vscode
        - import_role: name=benfiola.dotfiles.whatsapp
        - import_role: name=benfiola.dotfiles.xbox
        - import_role: name=benfiola.dotfiles.yubikey
        - import_role: name=benfiola.dotfiles.zsh
      always:
        - benfiola.dotfiles.temp_file_cleanup: {}
...