---
- tags: [optional, gimp]
  block:
    - when: not (darwin or archlinux or debian)
      block:
        - name: unimplemented
          benfiola.dotfiles.empty: {}

    - when: debian
      block:
        - name: apt install gimp
          become: true
          ansible.builtin.apt:
            package:
              - gimp

    - when: darwin
      block:
        - name: brew install homebrew/cask/gimp
          community.general.homebrew_cask:
            name: homebrew/cask/gimp
            path: "{{brew_path}}"

    - when: archlinux
      block:
        - name: pacman install gimp
          become: true
          community.general.pacman:
            name:
              - gimp
